export const styles = {
  page: {
    minHeight: "100vh",
    background: "#0a0a0f",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Space Mono', monospace",
    padding: "2rem",
  },
  header: {
    textAlign: "center",
    marginBottom: "2rem",
  },
  appTitle: {
    color: "#7c5cfc",
    fontSize: "2rem",
    fontWeight: 800,
  },
  appSub: {
    color: "#8888aa",
    fontSize: "0.85rem",
    marginTop: "0.3rem",
  },
  card: {
    background: "#13131a",
    border: "1px solid #2a2a3d",
    borderRadius: "12px",
    padding: "2.5rem",
    width: "100%",
    maxWidth: "420px",
  },
  title: {
    color: "#e8e8f0",
    fontSize: "1.5rem",
    fontWeight: 700,
    marginBottom: "0.3rem",
  },
  subtitle: {
    color: "#8888aa",
    fontSize: "0.85rem",
    marginBottom: "1.8rem",
  },
  fieldWrapper: {
    marginBottom: "1.2rem",
  },
  label: {
    display: "block",
    color: "#aaaacc",
    fontSize: "0.8rem",
    marginBottom: "0.4rem",
    letterSpacing: "0.05em",
  },
  input: {
    width: "100%",
    background: "#1c1c28",
    border: "1px solid #2a2a3d",
    borderRadius: "6px",
    color: "#e8e8f0",
    padding: "0.75rem 1rem",
    fontSize: "0.9rem",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "'Space Mono', monospace",
  },
  errorText: {
    color: "#fc5c7d",
    fontSize: "0.75rem",
    marginTop: "0.3rem",
  },
  button: {
    width: "100%",
    background: "#7c5cfc",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "0.85rem",
    fontSize: "0.9rem",
    fontWeight: 700,
    cursor: "pointer",
    marginTop: "0.5rem",
    fontFamily: "'Space Mono', monospace",
    letterSpacing: "0.05em",
  },
  successBox: {
    background: "rgba(46,125,50,0.15)",
    border: "1px solid #2e7d32",
    color: "#81c784",
    padding: "0.75rem 1rem",
    borderRadius: "6px",
    fontSize: "0.85rem",
    marginBottom: "1.2rem",
  },
  switchText: {
    color: "#8888aa",
    fontSize: "0.85rem",
    textAlign: "center",
    marginTop: "1.5rem",
  },
  link: {
    color: "#7c5cfc",
    cursor: "pointer",
    textDecoration: "underline",
  },
};
