const styles = {
  page: {
    minHeight: "100vh",
    background: "#0a0a0f",
    display: "flex",
    justifyContent: "center",
    padding: "3rem 1rem",
    fontFamily: "'Space Mono', monospace",
  },
  container: {
    width: "100%",
    maxWidth: "600px",
  },
  title: {
    color: "#e8e8f0",
    fontSize: "2rem",
    fontWeight: 800,
    marginBottom: "0.2rem",
  },
  subtitle: {
    color: "#7c5cfc",
    fontSize: "0.8rem",
    letterSpacing: "0.1em",
    marginBottom: "1.5rem",
  },
  stats: {
    display: "flex",
    gap: "1.5rem",
    marginBottom: "1.5rem",
    color: "#8888aa",
    fontSize: "0.85rem",
  },
  stat: {},
  addBar: {
    display: "flex",
    gap: "0.6rem",
    marginBottom: "1rem",
  },
  mainInput: {
    flex: 1,
    background: "#13131a",
    border: "1px solid #2a2a3d",
    borderRadius: "6px",
    color: "#e8e8f0",
    padding: "0.75rem 1rem",
    fontSize: "0.9rem",
    fontFamily: "'Space Mono', monospace",
    outline: "none",
  },
  select: {
    background: "#13131a",
    border: "1px solid #2a2a3d",
    borderRadius: "6px",
    color: "#e8e8f0",
    padding: "0.5rem",
    fontSize: "0.8rem",
    cursor: "pointer",
  },
  addBtn: {
    background: "#7c5cfc",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "0.75rem 1.2rem",
    fontSize: "0.85rem",
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'Space Mono', monospace",
  },
  filterBar: {
    display: "flex",
    gap: "0.4rem",
    marginBottom: "1.2rem",
  },
  filterBtn: {
    border: "1px solid #2a2a3d",
    borderRadius: "6px",
    padding: "0.4rem 1rem",
    fontSize: "0.8rem",
    cursor: "pointer",
    fontFamily: "'Space Mono', monospace",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "0.6rem",
  },
  todoItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    background: "#13131a",
    border: "1px solid #3d3d5c",
    borderRadius: "8px",
    padding: "0.9rem 1rem",
  },
  checkbox: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
    accentColor: "#7c5cfc",
    flexShrink: 0,
  },
  todoText: {
    flex: 1,
    fontSize: "0.9rem",
  },
  editInput: {
    flex: 1,
    background: "#1c1c28",
    border: "1px solid #7c5cfc",
    borderRadius: "4px",
    color: "#e8e8f0",
    padding: "0.3rem 0.6rem",
    fontSize: "0.9rem",
    fontFamily: "'Space Mono', monospace",
    outline: "none",
  },
  badge: {
    padding: "0.2rem 0.6rem",
    borderRadius: "4px",
    fontSize: "0.7rem",
    flexShrink: 0,
    letterSpacing: "0.05em",
  },
  actions: {
    display: "flex",
    gap: "0.4rem",
    flexShrink: 0,
  },
  btnEdit: {
    background: "transparent",
    border: "1px solid #2a2a3d",
    borderRadius: "4px",
    color: "#aaaacc",
    padding: "0.25rem 0.6rem",
    fontSize: "0.75rem",
    cursor: "pointer",
  },
  btnSave: {
    background: "rgba(124,92,252,0.2)",
    border: "1px solid #7c5cfc",
    borderRadius: "4px",
    color: "#7c5cfc",
    padding: "0.25rem 0.6rem",
    fontSize: "0.75rem",
    cursor: "pointer",
  },
  btnDelete: {
    background: "rgba(252,92,125,0.1)",
    border: "1px solid rgba(252,92,125,0.3)",
    borderRadius: "4px",
    color: "#fc5c7d",
    padding: "0.25rem 0.6rem",
    fontSize: "0.75rem",
    cursor: "pointer",
  },
  emptyMsg: {
    color: "#555577",
    textAlign: "center",
    padding: "2rem",
    fontSize: "0.9rem",
  },
  clearBtn: {
    marginTop: "1rem",
    background: "transparent",
    border: "1px solid #fc5c7d",
    borderRadius: "6px",
    color: "#fc5c7d",
    padding: "0.5rem 1.2rem",
    fontSize: "0.8rem",
    cursor: "pointer",
    fontFamily: "'Space Mono', monospace",
  },
};

export default styles;
